### ISSUE TITLE
dreambooth_ckpts

### ISSUE THREAD

**Issue by yuhaoliu7456** [vision-x-nyu/image-sculpting#9]
Great work. BTW, will you release the Lora weights in the future?

**Comment by domejiraphon** [comment]
Hi! We released the LORA weights in the zip file [here](https://drive.google.com/drive/u/1/folders/1cjUyssJaarYNpmY0pKxDGA4aOAlqZAad)

**Comment by yuhaoliu7456** [comment]
You mean the ckpt file in run.zip?

**Comment by yuhaoliu7456** [comment]
I just found these files. thx

**Comment by domejiraphon** [comment]
Nope, for example, it is in `runs/dreambooth_ckpts/astronaut1/pytorch_lora_weights.safetensors`
